name: uni_cart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.2
  provider: ^6.1.4
  smooth_page_indicator: ^1.2.1
  cloud_firestore: ^5.6.6
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  http: ^1.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/land_light.png
    - assets/images/land_dark.png
    - assets/images/first_light.png
    - assets/images/first_dark.png
    - assets/images/second_light.png
    - assets/images/second_dark.png
    - assets/images/third_light.png
    - assets/images/third_dark.png
    - assets/images/empty_light.png
    - assets/images/empty_dark.png
    - assets/images/list_empty_dark.png
    - assets/images/list_empty_light.png
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf