// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QM6Wl1CUZrc3qzW7b_eaPU2oyNHm4IM',
    appId: '1:839203736684:web:d5a96a68faa9e9f7b35c49',
    messagingSenderId: '839203736684',
    projectId: 'unicart-dbc61',
    authDomain: 'unicart-dbc61.firebaseapp.com',
    storageBucket: 'unicart-dbc61.firebasestorage.app',
    measurementId: 'G-TGT9NH73RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8HmP18CbBx5lWZLLyt-TTZ8Kxle4qwQ',
    appId: '1:839203736684:android:c79997117e5130f6b35c49',
    messagingSenderId: '839203736684',
    projectId: 'unicart-dbc61',
    storageBucket: 'unicart-dbc61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtJPQX4Ax6PwhrRmIpUJdNgQ9_8Q6Elk',
    appId: '1:839203736684:ios:68dbf9b73e3acf76b35c49',
    messagingSenderId: '839203736684',
    projectId: 'unicart-dbc61',
    storageBucket: 'unicart-dbc61.firebasestorage.app',
    iosBundleId: 'com.example.uniCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgtJPQX4Ax6PwhrRmIpUJdNgQ9_8Q6Elk',
    appId: '1:839203736684:ios:68dbf9b73e3acf76b35c49',
    messagingSenderId: '839203736684',
    projectId: 'unicart-dbc61',
    storageBucket: 'unicart-dbc61.firebasestorage.app',
    iosBundleId: 'com.example.uniCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QM6Wl1CUZrc3qzW7b_eaPU2oyNHm4IM',
    appId: '1:839203736684:web:61c1d8222a4c43b5b35c49',
    messagingSenderId: '839203736684',
    projectId: 'unicart-dbc61',
    authDomain: 'unicart-dbc61.firebaseapp.com',
    storageBucket: 'unicart-dbc61.firebasestorage.app',
    measurementId: 'G-7XTYPSL2VR',
  );
}
